// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace auto_update_data.database
{
    [Table("users")]
    public partial class Users
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("first_name")]
        [StringLength(100)]
        public string FirstName { get; set; }
        [Column("last_name")]
        [StringLength(100)]
        public string LastName { get; set; }
        [Column("email")]
        [StringLength(200)]
        public string Email { get; set; }
        [Column("home_address")]
        [StringLength(1000)]
        public string HomeAddress { get; set; }
    }
}